enh(log_v2): remove old logs REFS: MON-7362
centreon/centreon-broker pull request #618
Opened 2021-06-16 14:43 UTC by rem31

## Description

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-06-16 15:12 UTC, centreonpm commented on core/src/misc/diagnostic.cc
> +    log_v2::core()->info("diagnostic:     getting modules information");
strange spaces

2021-06-16 15:23 UTC, centreonpm commented on lua/src/macro_cache.cc
> +      sgm->group_name, sgm->group_id, sgm->host_id, sgm->service_id);
you forgot host_id in the text

2021-06-16 15:26 UTC, centreonpm commented on neb/src/initial.cc
> +        "init: error occurred while dumping host dependencies: ", e.what());
{} is missing

2021-06-16 15:28 UTC, centreonpm commented on neb/src/neb.cc
> +    log_v2::core()->error("main: cbmod loading failed: ", e.what());
{} is missing

2021-06-16 16:04 UTC, bouda1 requested changes

2021-06-17 07:47 UTC, bouda1 approved these changes

2021-06-17 08:54 UTC, merged